// Theme registry — must stay in sync with the [data-theme] blocks generated by
// scripts/gen-themes.mjs. Applied by setting `data-theme` on <html>.
export interface ThemeDef {
  id: string;
  label: string;
  scheme: 'light' | 'dark';
}

export const THEMES: ThemeDef[] = [
  // Dark — focus / low-light
  { id: 'amber', label: 'Amber', scheme: 'dark' },
  { id: 'dracula', label: 'Dracula', scheme: 'dark' },
  { id: 'tokyo-night', label: 'Tokyo Night', scheme: 'dark' },
  { id: 'nord', label: 'Nord', scheme: 'dark' },
  { id: 'catppuccin-mocha', label: 'Catppuccin Mocha', scheme: 'dark' },
  { id: 'one-dark', label: 'One Dark', scheme: 'dark' },
  // Light — daytime / reading / writing
  { id: 'paper', label: 'Paper (sepia)', scheme: 'light' },
  { id: 'solarized-light', label: 'Solarized Light', scheme: 'light' },
  { id: 'github-light', label: 'GitHub Light', scheme: 'light' },
  { id: 'catppuccin-latte', label: 'Catppuccin Latte', scheme: 'light' },
];

export const DARK_THEMES = THEMES.filter((t) => t.scheme === 'dark');
export const LIGHT_THEMES = THEMES.filter((t) => t.scheme === 'light');
