// Generates src/core/words.ts — typr's word bank used both to train the phonetic
// model and as the natural-words pool. Source: the top frequency words of the
// Google Web Trillion-Word Corpus (first20hours/google-10000-english, the
// "usa-no-swears" variant). Word-frequency data is factual; we filter for typing
// suitability, dedupe, keep frequency order, and take the top N.
//
// Regenerate:
//   curl -sL https://raw.githubusercontent.com/first20hours/google-10000-english/master/google-10000-english-usa-no-swears.txt > /tmp/words-raw.txt
//   node scripts/gen-words.mjs
import { readFileSync, writeFileSync } from 'node:fs';

const N = 5000;
const SRC = process.argv[2] || '/tmp/words-raw.txt';

const seen = new Set();
const words = [];
for (const raw of readFileSync(SRC, 'utf8').split(/\r?\n/)) {
  const w = raw.trim().toLowerCase();
  if (!/^[a-z]{2,12}$/.test(w)) continue; // typing-friendly: letters only, 2–12
  if (seen.has(w)) continue;
  seen.add(w);
  words.push(w);
  if (words.length >= N) break;
}

const lines = [];
for (let i = 0; i < words.length; i += 14) {
  lines.push(
    '  ' +
      words
        .slice(i, i + 14)
        .map((w) => `'${w}'`)
        .join(', ') +
      ',',
  );
}

const out = `// GENERATED by scripts/gen-words.mjs — do not edit by hand.
// Word bank: top ${words.length} frequency-ordered English words from the Google Web
// Trillion-Word Corpus (first20hours/google-10000-english, usa-no-swears), filtered
// to /^[a-z]{2,12}$/ and deduped. Frequency-ranked so common words are practiced
// first. Trains the phonetic model and serves as the natural-words pool. See
// docs/ATTRIBUTION.md.
export const WORDS: string[] = [
${lines.join('\n')}
];
`;

writeFileSync(new URL('../src/core/words.ts', import.meta.url), out);
const lens = words.map((w) => w.length);
console.log(
  `Wrote src/core/words.ts — ${words.length} words, length ${Math.min(...lens)}–${Math.max(...lens)} (avg ${(lens.reduce((a, b) => a + b, 0) / lens.length).toFixed(1)})`,
);
console.log('sample:', words.slice(0, 12).join(' '), '...', words.slice(-6).join(' '));
